const Data = [
  {
    id: 1,
    name: "Iphone",
    img: "./Images/iphone.jpg",
    price: 1200,
    quantity: 1,
  },
  {
    id: 2,
    name: "Tv",
    img: "./Images/tv.jpg",
    price: 10,
    quantity: 1,
  },
  {
    id: 3,
    name: "Samsung Mobile",
    img: "./Images/samsung.jpg",
    price: 200,
    quantity: 1,
  },
  {
    id: 4,
    name: "Bed",
    img: "./Images/bed.jpeg",
    price: 100,
    quantity: 1,
  },
  {
    id: 5,
    name: "Bike",
    img: "./Images/bike.webp",
    price: 1200,
    quantity: 1,
  },
  {
    id: 6,
    name: "Sofa",
    img: "./Images/sofa.jpg",
    price: 10,
    quantity: 1,
  },
  {
    id: 7,
    name: "Car",
    img: "./Images/car.jpg",
    price: 200,
    quantity: 1,
  },
  {
    id: 8,
    name: "Iphone",
    img: "./Images/iphone.jpg",
    price: 1200,
    quantity: 1,
  },
  {
    id: 9,
    name: "Tv",
    img: "./Images/tv.jpg",
    price: 10,
    quantity: 1,
  },
  {
    id: 10,
    name: "Samsung Mobile",
    img: "./Images/samsung.jpg",
    price: 200,
    quantity: 1,
  },
  {
    id: 11,
    name: "Bed",
    img: "./Images/bed.jpeg",
    price: 100,
    quantity: 1,
  },
  {
    id: 12,
    name: "Bike",
    img: "./Images/bike.webp",
    price: 1200,
    quantity: 1,
  },
  {
    id: 13,
    name: "Sofa",
    img: "./Images/sofa.jpg",
    price: 10,
    quantity: 1,
  },
  {
    id: 14,
    name: "Car",
    img: "./Images/car.jpg",
    price: 200,
    quantity: 1,
  },
];
export default Data;
